# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements-consumer.txt
RUN pip install --no-cache-dir -r requirements-consumer.txt

# Command to run on container start
CMD ["python", "consumer.py"]
